# Generated by Django 5.0.7 on 2024-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_drivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
