# Generated by Django 5.0.7 on 2024-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='collab',
            name='password',
            field=models.CharField(default=22, max_length=40),
            preserve_default=False,
        ),
    ]
