# Generated by Django 5.0.7 on 2024-07-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_collab_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='action',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
