# Generated by Django 5.0.7 on 2024-08-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernames', models.CharField(max_length=40)),
                ('pname', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('product', models.FileField(upload_to='')),
            ],
        ),
    ]
