# Generated by Django 5.0.7 on 2024-08-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('usernameu', models.CharField(max_length=40)),
                ('totalamount', models.IntegerField()),
                ('address', models.CharField(max_length=40)),
                ('uphone', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
                ('dusername', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameu', models.CharField(max_length=40)),
                ('totalamount', models.IntegerField()),
                ('dusername', models.CharField(max_length=40)),
            ],
        ),
    ]
